language: objective-c
xcode_project: GKNavigationBarExample.xcodeproj

env:
  global:
    - FRAMEWORK_NAME=GKNavigationBar
before_install:
  - gem install xcpretty
  
script:
  - xcodebuild -project $xcode_project -scheme $FRAMEWORK_NAME build | xcpretty
  - pod lib lint
  - carthage build --no-skip-current

notifications:
  email: false
